AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: MyHowm REST API
Globals:
  Function:
    Timeout: 3
Resources:
  MyHowmApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies: 
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
