AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Recipes REST API
Globals:
  Function:
    Timeout: 3
Resources:
  ExpressRecipesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies: 
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
      Events:
        RootPath:
          Type: Api
          Properties:
            Path: /recipes
            Method: any
        CatchAll:
          Type: Api
          Properties:
            Path: /recipes/{proxy+}
            Method: any
